### PR TITLE
Fix build for OSX

### PR DESCRIPTION
**Pull request by jameshilliard**
This should allow Armory to be compiled on OSX 10.11 El Capitan.

### CODE REVIEW

**Comment by ejpcmac** [comment]
In `compile_qt()` you should switch `qtBuildDir` and `qtTarFile` to the ones without `qtVerDate`.

**Comment by jameshilliard** [comment]
does that look good now?

**Comment by ejpcmac** [comment]
Yes, it’s good! It works fine now, I have re-checked by compiling from a fresh clone of your fix-osx-build branch.

We should also add to the build note (8) not to have a "brew"ed version of `libpng`. Armory kept crashing on launch until I unlinked `libpng` and re-compiled.

Thank you for your fix!

**Comment by Frank122480** [comment]
:-)

**Review by Frank122480 — APPROVED** [review]
Looks good now

**Pull request merged**
