### PR TITLE
Debian Package Static Linking

### PR DESCRIPTION
**Pull request by josephbisch**
This PR creates a deb package that should be installable on all Debian based Linux distros that have at least libc6 >= 2.14 (plus python >= 2.7 and the other non-versioned dependencies, but libc6 is the only one that should potentially be an issue).

I have tested installing and running the package with Debian Jessie. It should work with all Debian versions >= Jessie and all Ubuntu versions >= Precise, but it has only been tested with Jessie. It will definitely not work with Debian <= Wheezy or Ubuntu versions below Precise due to the libc6 version requirement.

This script just generates the actual Armory package. In its current state, when installing the resulting deb package, you need to either be online to fetch the dependencies, or you need to use some method of getting the dependencies from an online computer.

### CODE REVIEW

**Comment by josephbisch** [comment]
@droark - Forgot to mention your username so you would be notified about this PR, so I'm doing that now.

**Comment by josephbisch** [comment]
@droark - I tested the deb package with Ubuntu 12.04 and 14.04 and both work. The only problem is when starting Armory through the terminal on 12.04, there is no icon (just a question mark) on the left where there are all the program icons are. And when the question mark icon is moused over, it says ArmoryQt.py instead of Armory like I would expect. I'm not sure if this is a known issue or something new caused by the process by which I'm building the deb package.

**Comment by droark** [comment]
@josephbisch - Thanks for the heads up. I used to see something similar under OS X when I retooled how it was launched. The following comment from the startup script might help you. Otherwise, I'd just keep searching for another answer. I'm guessing the new setup does something subtle that causes this mismatch.

# OS X has a quirk. For whatever reasons, if you execute Python from a different
# location than the location of what actually gets executed when you run Armory,
# the menu bar calls Armory "Python". However, if you symlink Python and run the
# symlink from the execution directory, the app name from Info.plist is used.
# Also, the link should be here so that the link works wherever this is
# executed, and not just on the build machine.

On a different note, I asked about RPMs. If they're something you can easily add (e.g., 1-2 hours of work), that's fine. If they're going to take significant work, or require a strange build method, don't worry about it for now. RPMs are low priority for us.

**Comment by josephbisch** [comment]
@droark - I took a look at the 0.92.3 deb from bitcoinarmory.com and determined that there was a difference in the desktop files that already existed in the repository (so it actually had nothing to do with my build process).

I had to change the "Exec" line in the desktop files to be "python /usr/lib/armory/ArmoryQt.py %u" instead of "/usr/bin/armory %u". I have verified that it now works with 12.04 and 14.04.

So that change that I made in the last commit should probably also be made to 0.93-bugfix so that the issue is also fixed in any versions that may be released based on 0.93-bugfix.

The RPMs should be easy to do if we want something like the script that is being used for the deb packages currently available on the website. If the RPMs need to be reproducible, then I don't think that is going to happen in 2 hours with testing and all. Especially since I don't know how mature the Fedora reproducible effort is. So unless I hear otherwise, I'll go ahead with a script like the old deb script. That way there can be RPMs for those that really want them, but there can be a warning that they are not built reproducibly and therefore the deb packages are recommended over the RPMs. We can always use the script that I write as a start for reproducible RPMs if RPMs become more of a priority in the future.

**Comment by droark** [comment]
@josephbisch - As long as the script can be written quickly, I'm fine with it. The reproducible side of the equation isn't a big deal for now. In fact, to be honest, I'm not sure if this script would even be officially run. I believe the idea is to just kick off whatever needs to be built via Gitian, with everything else being second fiddle. RPMs would essentially be a curiosity for those willing to play around and accept the limitations.

Thanks for the exec fix. I'll probably put it in dev for now. Never say never but I don't think there will be a 0.93.2 release. Looks like we're going to try to get a 0.94 test build out soon-ish.

**Comment by droark** [comment]
@josephbisch - Looks pretty good overall. I'd like to merge this one once you've addressed my comments.

FYI, there may be some shifting of branches here and there in the coming week. We have a new setup we're following. Things may be a bit bumpy for a little while. Don't worry about it for now. Just giving you a heads up.

**Comment by josephbisch** [comment]
@droark - The last two commits I just made should address your comments.

**Pull request merged**
